#!/bin/bash
# Used to more neatly format dnsmasq leases file for reading.

arg=$1

if [[ "$1" = "-v" ]]
then
	cat /var/lib/misc/dnsmasq.leases
else
	cat /var/lib/misc/dnsmasq.leases | awk '{print $2,$3,$4}'
fi
