#!/bin/bash

# This script will set up the things I like on a new machine.

PASSWORD="INSERT_HERE"

if [ $PASSWORD == "INSERT_HERE" ]
then
	echo edit the password
	exit
fi

# Install software from repos

echo "::Installing software..."
for i in vim iftop git
	do dpkg -l $i > /dev/null && echo "    $i already installed" || sudo apt-get install -y --force-yes --no-install-recommends $i
done

echo "::Configuring git..."
# Set up my git settings for commits
git config --global user.name "Frank Petrilli"
git config --global user.email "frank@petril.li"
git config --global core.editor "vim"
git config --list | sed "s/^/    /"
# TODO:  Git clone my stuff. (Figure out how to do this securely)

echo "::Cloning MoveIn folder..."

#git clone http://git.petril.li/u/FrankPetrilli/MoveIn.git

# Also put things like vimrc into that folder.

# Set up my SSH access.

echo "::Copying SSH keys..."
if [ ! -d ~/.ssh ] 
then	
	mkdir ~/.ssh/
fi

if [ ! -f ~/.ssh/authorized_keys ]
then
	curl https://frank:$PASSWORD@frank.petril.li/files/Networking/authorized_keys > ~/.ssh/authorized_keys 2>/dev/null
else
	echo "    authorized_keys already exists"
fi

chmod 600 ~/.ssh/authorized_keys
echo `cat ~/.ssh/authorized_keys | wc -l` lines in ~/.ssh/authorized_keys | sed "s/^/    /"
